# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

Organizations:
    - &OrdererOrg
        Name: OrdererMSP
        ID: OrdererMSP
        MSPDir: build/crypto-config/ordererOrganizations/smartm2m.co.kr/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"
    - &PusanOrg
        Name: PusanMSP
        ID: PusanMSP
        MSPDir: build/crypto-config/peerOrganizations/pusan.smartm2m.co.kr/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('PusanMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('PusanMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('PusanMSP.admin')"
        AnchorPeers:
            - Host: peer0.pusan.smartm2m.co.kr
              Port: 7051
    - &UlsanOrg
        Name: UlsanMSP
        ID: UlsanMSP
        MSPDir: build/crypto-config/peerOrganizations/ulsan.smartm2m.co.kr/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('UlsanMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('UlsanMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('UlsanMSP.admin')"
        AnchorPeers:
            - Host: peer0.ulsan.smartm2m.co.kr
              Port: 7051
    - &SeoulOrg
        Name: SeoulMSP
        ID: SeoulMSP
        MSPDir: build/crypto-config/peerOrganizations/seoul.smartm2m.co.kr/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('SeoulMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('SeoulMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('SeoulMSP.admin')"
        AnchorPeers:
            - Host: peer0.seoul.smartm2m.co.kr
              Port: 7051

Capabilities:
    Channel: &ChannelCapabilities
        V1_4_3: true
        V1_3: false
        V1_1: false

    Orderer: &OrdererCapabilities
        V1_4_2: true
        V1_1: false

    Application: &ApplicationCapabilities
        V1_4_2: true
        V1_3: false
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults
    Policies: &ApplicationDefaultPolicies
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: etcdraft
    Addresses:
        - orderer0.smartm2m.co.kr:7050
        - orderer1.smartm2m.co.kr:7050
        - orderer2.smartm2m.co.kr:7050
    EtcdRaft:
        Consenters:
            - Host: orderer0.smartm2m.co.kr
              Port: 7050
              ClientTLSCert: build/crypto-config/ordererOrganizations/smartm2m.co.kr/orderers/orderer0.smartm2m.co.kr/tls/server.crt
              ServerTLSCert: build/crypto-config/ordererOrganizations/smartm2m.co.kr/orderers/orderer0.smartm2m.co.kr/tls/server.crt
            - Host: orderer1.smartm2m.co.kr
              Port: 7050
              ClientTLSCert: build/crypto-config/ordererOrganizations/smartm2m.co.kr/orderers/orderer1.smartm2m.co.kr/tls/server.crt
              ServerTLSCert: build/crypto-config/ordererOrganizations/smartm2m.co.kr/orderers/orderer1.smartm2m.co.kr/tls/server.crt
            - Host: orderer2.smartm2m.co.kr
              Port: 7050
              ClientTLSCert: build/crypto-config/ordererOrganizations/smartm2m.co.kr/orderers/orderer2.smartm2m.co.kr/tls/server.crt
              ServerTLSCert: build/crypto-config/ordererOrganizations/smartm2m.co.kr/orderers/orderer2.smartm2m.co.kr/tls/server.crt
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 98 MB
        PreferredMaxBytes: 512 KB
    MaxChannels: 0
    Organizations:
        - *OrdererOrg
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
    Capabilities:
        <<: *OrdererCapabilities

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    MainChannel:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
            - <<: *OrdererOrg
        Consortiums:
            BlockMasterConsortium:
                Organizations:
                    - *PusanOrg
                    - *UlsanOrg
                    - *SeoulOrg
    TestChannelA:
        Consortium: BlockMasterConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *PusanOrg
                - *UlsanOrg
    TestChannelB:
        Consortium: BlockMasterConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *PusanOrg
                - *SeoulOrg
    TestChannelC:
        Consortium: BlockMasterConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *UlsanOrg
                - *SeoulOrg
