version: '3'

networks:
  default:
    external:
      name: blockchain

services:
  ca.pusan.smartm2m.co.kr:
    restart: always
    container_name: ca.pusan.smartm2m.co.kr
    image: hyperledger/fabric-ca:1.4.8
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.pusan.smartm2m.co.kr
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.pusan.smartm2m.co.kr-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${ca_pusan_private_key}

      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.pusan.smartm2m.co.kr-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${ca_pusan_private_key}
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./build/crypto-config/peerOrganizations/pusan.smartm2m.co.kr/ca:/etc/hyperledger/fabric-ca-server-config
    ports:
      - 7054:7054

  ca.ulsan.smartm2m.co.kr:
    restart: always
    container_name: ca.ulsan.smartm2m.co.kr
    image: hyperledger/fabric-ca:1.4.8
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.ulsan.smartm2m.co.kr
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.ulsan.smartm2m.co.kr-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${ca_ulsan_private_key}

      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.ulsan.smartm2m.co.kr-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${ca_ulsan_private_key}
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./build/crypto-config/peerOrganizations/ulsan.smartm2m.co.kr/ca:/etc/hyperledger/fabric-ca-server-config
    ports:
      - 8054:7054

  ca.seoul.smartm2m.co.kr:
      restart: always
      container_name: ca.seoul.smartm2m.co.kr
      image: hyperledger/fabric-ca:1.4.8
      environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        - FABRIC_CA_SERVER_CA_NAME=ca.seoul.smartm2m.co.kr
        - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.seoul.smartm2m.co.kr-cert.pem
        - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${ca_seoul_private_key}

        - FABRIC_CA_SERVER_TLS_ENABLED=true
        - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.seoul.smartm2m.co.kr-cert.pem
        - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${ca_seoul_private_key}
      command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
      volumes:
        - ./build/crypto-config/peerOrganizations/seoul.smartm2m.co.kr/ca:/etc/hyperledger/fabric-ca-server-config
      ports:
        - 9054:7054

  orderer0.smartm2m.co.kr:
    restart: always
    container_name: orderer0.smartm2m.co.kr
    image: hyperledger/fabric-orderer:1.4.8
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - ORDERER_GENERAL_LOCALMSPDIR=build/crypto-config/ordererOrganizations/smartm2m.co.kr/orderers/orderer0.smartm2m.co.kr/msp
      # TLS
      - ORDERER_GENERAL_TLS_PRIVATEKEY=build/crypto-config/ordererOrganizations/smartm2m.co.kr/orderers/orderer0.smartm2m.co.kr/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=build/crypto-config/ordererOrganizations/smartm2m.co.kr/orderers/orderer0.smartm2m.co.kr/tls/server.crt

      # etcdraft
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=build/crypto-config/ordererOrganizations/smartm2m.co.kr/orderers/orderer0.smartm2m.co.kr/tls/server.key
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=build/crypto-config/ordererOrganizations/smartm2m.co.kr/orderers/orderer0.smartm2m.co.kr/tls/server.crt
    working_dir: /etc/hyperledger/fabric
    volumes:
      - ./:/etc/hyperledger/fabric
    ports:
      - 7050:7050

  orderer1.smartm2m.co.kr:
    restart: always
    container_name: orderer1.smartm2m.co.kr
    image: hyperledger/fabric-orderer:1.4.8
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - ORDERER_GENERAL_LOCALMSPDIR=build/crypto-config/ordererOrganizations/smartm2m.co.kr/orderers/orderer1.smartm2m.co.kr/msp
      # TLS
      - ORDERER_GENERAL_TLS_PRIVATEKEY=build/crypto-config/ordererOrganizations/smartm2m.co.kr/orderers/orderer1.smartm2m.co.kr/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=build/crypto-config/ordererOrganizations/smartm2m.co.kr/orderers/orderer1.smartm2m.co.kr/tls/server.crt

      # etcdraft
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=build/crypto-config/ordererOrganizations/smartm2m.co.kr/orderers/orderer1.smartm2m.co.kr/tls/server.key
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=build/crypto-config/ordererOrganizations/smartm2m.co.kr/orderers/orderer1.smartm2m.co.kr/tls/server.crt
    working_dir: /etc/hyperledger/fabric
    volumes:
      - ./:/etc/hyperledger/fabric
    ports:
      - 8050:7050

  orderer2.smartm2m.co.kr:
    restart: always
    container_name: orderer2.smartm2m.co.kr
    image: hyperledger/fabric-orderer:1.4.8
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - ORDERER_GENERAL_LOCALMSPDIR=build/crypto-config/ordererOrganizations/smartm2m.co.kr/orderers/orderer2.smartm2m.co.kr/msp
      # TLS
      - ORDERER_GENERAL_TLS_PRIVATEKEY=build/crypto-config/ordererOrganizations/smartm2m.co.kr/orderers/orderer2.smartm2m.co.kr/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=build/crypto-config/ordererOrganizations/smartm2m.co.kr/orderers/orderer2.smartm2m.co.kr/tls/server.crt

      # etcdraft
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=build/crypto-config/ordererOrganizations/smartm2m.co.kr/orderers/orderer2.smartm2m.co.kr/tls/server.key
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=build/crypto-config/ordererOrganizations/smartm2m.co.kr/orderers/orderer2.smartm2m.co.kr/tls/server.crt
    working_dir: /etc/hyperledger/fabric
    volumes:
      - ./:/etc/hyperledger/fabric
    ports:
      - 9050:7050

  couchdb.peer0.pusan.smartm2m.co.kr:
    restart: always
    container_name: couchdb.peer0.pusan.smartm2m.co.kr
    image: hyperledger/fabric-couchdb:0.4.20
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    ports:
      - 7984:5984

  peer0.pusan.smartm2m.co.kr:
    restart: always
    container_name: peer0.pusan.smartm2m.co.kr
    image: hyperledger/fabric-peer:1.4.8
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_PEER_ID=peer0.pusan.smartm2m.co.kr
      - CORE_PEER_ADDRESS=peer0.pusan.smartm2m.co.kr:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.pusan.smartm2m.co.kr:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.pusan.smartm2m.co.kr:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.pusan.smartm2m.co.kr:7051

      - CORE_PEER_TLS_CERT_FILE=build/crypto-config/peerOrganizations/pusan.smartm2m.co.kr/peers/peer0.pusan.smartm2m.co.kr/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=build/crypto-config/peerOrganizations/pusan.smartm2m.co.kr/peers/peer0.pusan.smartm2m.co.kr/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=build/crypto-config/peerOrganizations/pusan.smartm2m.co.kr/peers/peer0.pusan.smartm2m.co.kr/tls/ca.crt

      - CORE_PEER_TLS_CLIENTCERT_FILE=build/crypto-config/peerOrganizations/pusan.smartm2m.co.kr/users/Admin@pusan.smartm2m.co.kr/tls/client.crt
      - CORE_PEER_TLS_CLIENTKEY_FILE=build/crypto-config/peerOrganizations/pusan.smartm2m.co.kr/users/Admin@pusan.smartm2m.co.kr/tls/client.key
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=build/crypto-config/peerOrganizations/pusan.smartm2m.co.kr/users/Admin@pusan.smartm2m.co.kr/tls/ca.crt

      - CORE_PEER_MSPCONFIGPATH=build/crypto-config/peerOrganizations/pusan.smartm2m.co.kr/peers/peer0.pusan.smartm2m.co.kr/msp
      - CORE_PEER_LOCALMSPID=pusanMSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.pusan.smartm2m.co.kr:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password
    working_dir: /etc/hyperledger/fabric
    volumes:
      - ./:/etc/hyperledger/fabric
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053

  couchdb.peer0.ulsan.smartm2m.co.kr:
    restart: always
    container_name: couchdb.peer0.ulsan.smartm2m.co.kr
    image: hyperledger/fabric-couchdb:0.4.20
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    ports:
      - 8984:5984

  peer0.ulsan.smartm2m.co.kr:
    restart: always
    container_name: peer0.ulsan.smartm2m.co.kr
    image: hyperledger/fabric-peer:1.4.8
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_PEER_ID=peer0.ulsan.smartm2m.co.kr
      - CORE_PEER_ADDRESS=peer0.ulsan.smartm2m.co.kr:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.ulsan.smartm2m.co.kr:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.ulsan.smartm2m.co.kr:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ulsan.smartm2m.co.kr:7051

      - CORE_PEER_TLS_CERT_FILE=build/crypto-config/peerorganizations/ulsan.smartm2m.co.kr/peers/peer0.ulsan.smartm2m.co.kr/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=build/crypto-config/peerOrganizations/ulsan.smartm2m.co.kr/peers/peer0.ulsan.smartm2m.co.kr/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=build/crypto-config/peerOrganizations/ulsan.smartm2m.co.kr/peers/peer0.ulsan.smartm2m.co.kr/tls/ca.crt

      - CORE_PEER_TLS_CLIENTCERT_FILE=build/crypto-config/peerOrganizations/ulsan.smartm2m.co.kr/users/Admin@ulsan.smartm2m.co.kr/tls/client.crt
      - CORE_PEER_TLS_CLIENTKEY_FILE=build/crypto-config/peerOrganizations/ulsan.smartm2m.co.kr/users/Admin@ulsan.smartm2m.co.kr/tls/client.key
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=build/crypto-config/peerOrganizations/ulsan.smartm2m.co.kr/users/Admin@ulsan.smartm2m.co.kr/tls/ca.crt

      - CORE_PEER_MSPCONFIGPATH=build/crypto-config/peerOrganizations/ulsan.smartm2m.co.kr/peers/peer0.ulsan.smartm2m.co.kr/msp
      - CORE_PEER_LOCALMSPID=ulsanMSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.ulsan.smartm2m.co.kr:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password
    working_dir: /etc/hyperledger/fabric
    volumes:
      - ./:/etc/hyperledger/fabric
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8051:7051
      - 8052:7052
      - 8053:7053

  couchdb.peer0.seoul.smartm2m.co.kr:
    restart: always
    container_name: couchdb.peer0.seoul.smartm2m.co.kr
    image: hyperledger/fabric-couchdb:0.4.20
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    ports:
      - 9984:5984

  peer0.seoul.smartm2m.co.kr:
    restart: always
    container_name: peer0.seoul.smartm2m.co.kr
    image: hyperledger/fabric-peer:1.4.8
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_PEER_ID=peer0.seoul.smartm2m.co.kr
      - CORE_PEER_ADDRESS=peer0.seoul.smartm2m.co.kr:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.seoul.smartm2m.co.kr:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.seoul.smartm2m.co.kr:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.seoul.smartm2m.co.kr:7051

      - CORE_PEER_TLS_CERT_FILE=build/crypto-config/peerOrganizations/seoul.smartm2m.co.kr/peers/peer0.seoul.smartm2m.co.kr/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=build/crypto-config/peerOrganizations/seoul.smartm2m.co.kr/peers/peer0.seoul.smartm2m.co.kr/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=build/crypto-config/peerOrganizations/seoul.smartm2m.co.kr/peers/peer0.seoul.smartm2m.co.kr/tls/ca.crt

      - CORE_PEER_TLS_CLIENTCERT_FILE=build/crypto-config/peerOrganizations/seoul.smartm2m.co.kr/users/Admin@seoul.smartm2m.co.kr/tls/client.crt
      - CORE_PEER_TLS_CLIENTKEY_FILE=build/crypto-config/peerOrganizations/seoul.smartm2m.co.kr/users/Admin@seoul.smartm2m.co.kr/tls/client.key
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=build/crypto-config/peerOrganizations/seoul.smartm2m.co.kr/users/Admin@seoul.smartm2m.co.kr/tls/ca.crt

      - CORE_PEER_MSPCONFIGPATH=build/crypto-config/peerOrganizations/seoul.smartm2m.co.kr/peers/peer0.seoul.smartm2m.co.kr/msp
      - CORE_PEER_LOCALMSPID=seoulMSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.seoul.smartm2m.co.kr:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password
    working_dir: /etc/hyperledger/fabric
    volumes:
      - ./:/etc/hyperledger/fabric
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9051:7051
      - 9052:7052
      - 9053:7053

  cli.smartm2m.co.kr:
    restart: always
    container_name: cli.smartm2m.co.kr
    image: hyperledger/fabric-tools:1.4.8
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_PEER_MSPCONFIGPATH=build/crypto-config/peerOrganizations/pusan.smartm2m.co.kr/peers/peer0.pusan.smartm2m.co.kr/msp
      - CORE_PEER_LOCALMSPID=pusanMSP
      - CORE_PEER_ID=cli.smartm2m.co.kr
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=cli.smartm2m.co.kr:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=cli.smartm2m.co.kr:7051
      - CORE_LEDGER_STATE_STATEDATABASE=goleveldb

      - CORE_PEER_TLS_CERT_FILE=build/crypto-config/peerOrganizations/pusan.smartm2m.co.kr/peers/peer0.pusan.smartm2m.co.kr/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=build/crypto-config/peerOrganizations/pusan.smartm2m.co.kr/peers/peer0.pusan.smartm2m.co.kr/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=build/crypto-config/peerOrganizations/pusan.smartm2m.co.kr/peers/peer0.pusan.smartm2m.co.kr/tls/ca.crt

      - CORE_PEER_TLS_CLIENTCERT_FILE=build/crypto-config/peerOrganizations/pusan.smartm2m.co.kr/users/Admin@pusan.smartm2m.co.kr/tls/client.crt
      - CORE_PEER_TLS_CLIENTKEY_FILE=build/crypto-config/peerOrganizations/pusan.smartm2m.co.kr/users/Admin@pusan.smartm2m.co.kr/tls/client.key
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=build/crypto-config/peerOrganizations/pusan.smartm2m.co.kr/users/Admin@pusan.smartm2m.co.kr/tls/ca.crt

    working_dir: /etc/hyperledger/fabric
    command: sh -c "peer node start"
    volumes:
      - ./:/etc/hyperledger/fabric
      - /var/run/docker.sock:/var/run/docker.sock
      - ${GOPATH}:/opt/gopath
